### ISSUE TITLE
How can I use it in Typescript using Ionic 4??

### ISSUE THREAD

**Issue by Ragul184** [jens-duttke/jsqr#2]
Im currently developing a ionic event manager app which requires qr generator... I dont know how to use this jsQR for generating QR in ionic 4... If anyone knows kindly please respond to this and clear my doubts...

**Comment by scionGhb** [comment]
Hi there, TypeScript works over JavaScript so JavaScript code should works even if you are using TypeScript.

**Comment by jens-duttke** [comment]
I assume the question has been answered, so I'll close this issue.
